### Get Employees
GET http://localhost:8080/api/v1/employees?page=0&size=100


### Create Employee
POST http://localhost:8080/api/v1/employees
Content-Type: application/json

{
  "firstName": "Mehmet",
  "lastName": "Demir",
  "email": "mehmet.demir@nextalx.com",
  "phone": "05551234567",
  "jobTitle": "Frontend Developer",
  "status": "ACTIVE",
  "departmentId": 1
}


### Update Employee
PUT http://localhost:8080/api/v1/employees/1
Content-Type: application/json

{
  "firstName": "Ahmet",
  "lastName": "Yılmaz",
  "email": "ahmet@nextalx.com",
  "phone": "05559998877",
  "jobTitle": "Senior Backend Developer",
  "status": "ACTIVE",
  "departmentId": 1
}


### Deactivate Employee
PATCH http://localhost:8080/api/v1/employees/1/deactivate


### Activate Employee
PATCH http://localhost:8080/api/v1/employees/1/activate